//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jury
    {
        public int JuryID { get; set; }
        public int UserID { get; set; }
        public int ActivityID { get; set; }
        public string Specialization { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
