//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderators
    {
        public int ModeratorID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> ActivityID { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual Users Users { get; set; }
    }
}
