//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferenceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizers
    {
        public int OrganizerID { get; set; }
        public int UserID { get; set; }
        public int EventID { get; set; }
        public int ActivityID { get; set; }
    
        public virtual Activities Activities { get; set; }
        public virtual Events Events { get; set; }
        public virtual Users Users { get; set; }
    }
}
